<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transaction Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .logo {
            max-width: 150px;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 24px;
            margin: 0 0 5px;
            color: #2563eb;
        }
        .subtitle {
            font-size: 14px;
            color: #666;
            margin: 0 0 5px;
        }
        .meta {
            margin-bottom: 20px;
        }
        .meta-item {
            margin-bottom: 5px;
            font-size: 12px;
        }
        .meta-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 12px;
        }
        th {
            background-color: #f3f4f6;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #eee;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .summary {
            margin-bottom: 30px;
        }
        .summary h2 {
            font-size: 18px;
            margin: 0 0 10px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        .summary-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
        }
        .summary-item {
            flex: 1;
            min-width: 150px;
            padding: 10px;
            background-color: #f9fafb;
            border-radius: 5px;
            border: 1px solid #eee;
        }
        .summary-label {
            font-size: 12px;
            color: #666;
        }
        .summary-value {
            font-size: 18px;
            font-weight: bold;
            margin-top: 5px;
        }
        .footer {
            text-align: center;
            font-size: 11px;
            color: #666;
            margin-top: 30px;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        .pending {
            background-color: #fef3c7;
            color: #92400e;
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 10px;
        }
        .completed {
            background-color: #d1fae5;
            color: #065f46;
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 10px;
        }
        .cancelled {
            background-color: #fee2e2;
            color: #b91c1c;
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 10px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Transaction Report</h1>
        <p class="subtitle">Comprehensive transaction data report for the veterinary practice</p>
    </div>

    <div class="meta">
        <div class="meta-item">
            <span class="meta-label">Report Period:</span>
            {{ $dateFrom->format('M d, Y') }} - {{ $dateTo->format('M d, Y') }}
        </div>
        <div class="meta-item">
            <span class="meta-label">Generated By:</span>
            {{ $receptionist->complete_name }}
        </div>
        <div class="meta-item">
            <span class="meta-label">Generated On:</span>
            {{ now()->format('M d, Y h:i A') }}
        </div>
        <div class="meta-item">
            <span class="meta-label">Filters Applied:</span>
            Type: {{ $filters['type'] }}, 
            Subtype: {{ $filters['subtype'] }}, 
            Status: {{ $filters['status'] }}
        </div>
    </div>

    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-label">Total Transactions</div>
                <div class="summary-value">{{ $summary['total'] }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Completed</div>
                <div class="summary-value">{{ $summary['byStatus']['completed'] }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Pending</div>
                <div class="summary-value">{{ $summary['byStatus']['pending'] }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Cancelled</div>
                <div class="summary-value">{{ $summary['byStatus']['cancelled'] }}</div>
            </div>
        </div>
    </div>

    @if($summary['byType']->isNotEmpty())
    <div class="summary">
        <h2>By Transaction Type</h2>
        <table>
            <thead>
                <tr>
                    <th>Transaction Type</th>
                    <th>Total</th>
                    <th>Completed</th>
                    <th>Pending</th>
                    <th>Cancelled</th>
                </tr>
            </thead>
            <tbody>
                @foreach($summary['byType'] as $type => $data)
                <tr>
                    <td><strong>{{ $type }}</strong></td>
                    <td>{{ $data['count'] }}</td>
                    <td>{{ $data['completed'] }}</td>
                    <td>{{ $data['pending'] }}</td>
                    <td>{{ $data['cancelled'] }}</td>
                </tr>
                    @if(isset($data['bySubtype']) && $data['bySubtype']->isNotEmpty())
                        @foreach($data['bySubtype'] as $subtype => $subData)
                        <tr>
                            <td>&nbsp;&nbsp;- {{ $subtype ?: 'No Subtype' }}</td>
                            <td>{{ $subData['count'] }}</td>
                            <td>{{ $subData['completed'] }}</td>
                            <td>{{ $subData['pending'] }}</td>
                            <td>{{ $subData['cancelled'] }}</td>
                        </tr>
                        @endforeach
                    @endif
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <h2>Transaction Details</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Transaction ID</th>
                <th>Owner</th>
                <th>Animal</th>
                <th>Type</th>
                <th>Subtype</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $transaction)
            <tr>
                <td>{{ $transaction->created_at->format('M d, Y') }}</td>
                <td>{{ $transaction->transaction_id }}</td>
                <td>{{ optional(optional($transaction->owner)->user)->complete_name ?? 'N/A' }}</td>
                <td>{{ optional($transaction->animal)->name ?? 'N/A' }}</td>
                <td>{{ optional($transaction->transactionType)->type_name ?? 'N/A' }}</td>
                <td>{{ optional($transaction->transactionSubtype)->subtype_name ?? 'N/A' }}</td>
                <td>
                    @if($transaction->status === 0)
                    <span class="pending">Pending</span>
                    @elseif($transaction->status === 1)
                    <span class="completed">Completed</span>
                    @else
                    <span class="cancelled">Cancelled</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center;">No transactions found matching the criteria.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was automatically generated on {{ now()->format('F d, Y h:i A') }}.</p>
        <p>© {{ date('Y') }} Veterinary Practice Management System</p>
    </div>
</body>
</html>